if(EXISTS "D:/Code/IMDb-Top250-Recommender/build_bench/test_minheap[1]_tests.cmake")
  include("D:/Code/IMDb-Top250-Recommender/build_bench/test_minheap[1]_tests.cmake")
else()
  add_test(test_minheap_NOT_BUILT test_minheap_NOT_BUILT)
endif()
